language: haxe
haxe:
  - "3.2.1"
  - development
neko: "2.0.0"
matrix:
  allow_failures:
    - haxe: development # Allow development to fail until I have time to investigate.
env:
  - MYSQL_HOST="127.0.0.1" MYSQL_PORT="3306" MYSQL_USER="root" MYSQL_PASSWORD="" MYSQL_DATABASE="test" # For ufront-orm tests
before_install:
  - sudo add-apt-repository ppa:ondrej/php5 -y
  - sudo apt-get update -q
  - sudo apt-get install php5-cli php5-sqlite php5-mysql libsqlite3-0 libsqlite3-dev
  - mysql -e "create database IF NOT EXISTS test;" -uroot # For ufront-orm tests.
install:
  - yes | haxelib install doc.hxml # Haxelibs we need installed.
  - yes | haxelib git dox https://github.com/dpeek/dox.git # For compiling API docs.
  - haxelib list
script:
  - ./runtests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bcd2c2de221af91a76a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
